import nodemailer from 'nodemailer';
import type { Transporter } from 'nodemailer';

export interface EmailConfig {
  host: string;
  port: number;
  secure: boolean;
  auth: {
    user: string;
    pass: string;
  };
}

export interface SendEmailOptions {
  to: string;
  subject: string;
  text?: string;
  html?: string;
  attachments?: Array<{
    filename: string;
    content: Buffer | Uint8Array;
    contentType?: string;
  }>;
}

/**
 * Get email configuration from environment variables
 */
function getEmailConfig(): EmailConfig | null {
  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || '587');
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    return null;
  }

  return {
    host,
    port,
    secure: port === 465,
    auth: { user, pass }
  };
}

/**
 * Create email transporter
 */
function createTransporter(): Transporter | null {
  const config = getEmailConfig();
  if (!config) {
    console.warn('Email configuration not found. Set SMTP_HOST, SMTP_USER, SMTP_PASS');
    return null;
  }

  return nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: config.auth
  });
}

/**
 * Send email
 */
export async function sendEmail(options: SendEmailOptions): Promise<boolean> {
  const transporter = createTransporter();
  if (!transporter) {
    console.error('Email transporter not configured');
    return false;
  }

  const fromAddress = process.env.SMTP_FROM || process.env.SMTP_USER || 'report@llm-trace-lens.com';

  try {
    const info = await transporter.sendMail({
      from: fromAddress,
      to: options.to,
      subject: options.subject,
      text: options.text,
      html: options.html,
      attachments: options.attachments?.map(att => ({
        filename: att.filename,
        content: Buffer.from(att.content),
        contentType: att.contentType
      }))
    });

    console.log(`Email sent: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error('Failed to send email:', error);
    return false;
  }
}

/**
 * Send monthly report email
 */
export async function sendMonthlyReportEmail(
  to: string,
  month: string,
  pdfBuffer: Uint8Array,
  workspaceId: string
): Promise<boolean> {
  const subject = `LLM Trace Lens Monthly Report - ${month}`;

  const html = `
    <h1>Monthly Report - ${month}</h1>
    <p>Your LLM Trace Lens monthly report is attached.</p>
    <p>
      <strong>Workspace:</strong> ${workspaceId}<br>
      <strong>Period:</strong> ${month}
    </p>
    <p>This report includes:</p>
    <ul>
      <li>Total requests and costs</li>
      <li>Cost breakdown by provider and model</li>
      <li>Validation summary</li>
      <li>Average latency metrics</li>
    </ul>
    <hr>
    <p style="color: #666; font-size: 12px;">
      Generated by LLM Trace Lens<br>
      <a href="https://github.com/your-repo/llm-trace-lens">View on GitHub</a>
    </p>
  `;

  const text = `
Monthly Report - ${month}

Your LLM Trace Lens monthly report is attached.

Workspace: ${workspaceId}
Period: ${month}

This report includes:
- Total requests and costs
- Cost breakdown by provider and model
- Validation summary
- Average latency metrics

Generated by LLM Trace Lens
`;

  return sendEmail({
    to,
    subject,
    html,
    text,
    attachments: [
      {
        filename: `llm-trace-lens-report-${month}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf'
      }
    ]
  });
}

/**
 * Send test email to verify configuration
 */
export async function sendTestEmail(to: string): Promise<boolean> {
  return sendEmail({
    to,
    subject: 'LLM Trace Lens - Test Email',
    text: 'This is a test email from LLM Trace Lens. If you received this, your email configuration is working correctly.',
    html: `
      <h1>Test Email</h1>
      <p>This is a test email from LLM Trace Lens.</p>
      <p>If you received this, your email configuration is working correctly.</p>
    `
  });
}

/**
 * Check if email is configured
 */
export function isEmailConfigured(): boolean {
  return getEmailConfig() !== null;
}
