/**
 * gmail.ts — Gmail connector.
 *
 * Actions:
 *   - draftEmail : create a draft in the user's Drafts folder
 *   - sendEmail  : send an email immediately
 *
 * Both actions accept:
 *   { to: string|string[], subject: string, body: string,
 *     cc?, bcc?, attachments?: [{ filename, mimeType, base64 }] }
 *
 * v1 keeps attachment handling minimal (base64 inline) because the primary
 * use case is PDFs generated by the AI Employee document tools — those are
 * already produced as binary buffers on the server side.
 */
import {
  loadConnectorToken,
  isConnectorLinked,
} from '../auth/oauth/oauth-flow.js';
import {
  createGoogleOAuth2Client,
  loadGoogleOAuthConfig,
  GOOGLE_GMAIL_SCOPES,
} from '../auth/oauth/google-oauth.js';
import { google } from 'googleapis';
import type { Connector, ConnectorActionResult } from './base.js';
import { connectorOk, connectorErr } from './base.js';

const ACTIONS = ['draftEmail', 'sendEmail'] as const;
type GmailAction = (typeof ACTIONS)[number];

function isGmailAction(value: string): value is GmailAction {
  return (ACTIONS as readonly string[]).includes(value);
}

// ---------------------------------------------------------------------------
// Param shapes
// ---------------------------------------------------------------------------

interface AttachmentInput {
  filename: string;
  mimeType: string;
  base64: string;
}

interface EmailParams {
  to: string | string[];
  subject: string;
  body: string;
  cc?: string | string[];
  bcc?: string | string[];
  attachments?: AttachmentInput[];
}

function isStringOrStringArray(value: unknown): value is string | string[] {
  if (typeof value === 'string') return true;
  return Array.isArray(value) && value.every((v) => typeof v === 'string');
}

function isAttachment(value: unknown): value is AttachmentInput {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.filename === 'string' &&
    typeof v.mimeType === 'string' &&
    typeof v.base64 === 'string'
  );
}

function isEmailParams(value: unknown): value is EmailParams {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  if (!isStringOrStringArray(v.to)) return false;
  if (typeof v.subject !== 'string') return false;
  if (typeof v.body !== 'string') return false;
  if (v.cc !== undefined && !isStringOrStringArray(v.cc)) return false;
  if (v.bcc !== undefined && !isStringOrStringArray(v.bcc)) return false;
  if (v.attachments !== undefined) {
    if (!Array.isArray(v.attachments)) return false;
    if (!v.attachments.every(isAttachment)) return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// Gmail client
// ---------------------------------------------------------------------------

async function buildGmailClient(userId: string) {
  const bundle = await loadConnectorToken(userId, 'google');
  if (!bundle) return null;
  const config = loadGoogleOAuthConfig('');
  const oauth2 = createGoogleOAuth2Client(config);
  oauth2.setCredentials({
    access_token: bundle.accessToken,
    refresh_token: bundle.refreshToken ?? undefined,
    expiry_date: bundle.expiresAt ? bundle.expiresAt.getTime() : undefined,
  });
  return google.gmail({ version: 'v1', auth: oauth2 });
}

// ---------------------------------------------------------------------------
// MIME construction
// ---------------------------------------------------------------------------

/**
 * Reject header values containing CR/LF to prevent MIME header injection
 * (QA Finding S-02, 2026-04-20). Also reject quotes in filenames that would
 * break out of the attachment header structure.
 */
function assertNoHeaderInjection(value: string, field: string): void {
  if (/[\r\n]/.test(value)) {
    throw new Error(`[gmail] invalid ${field}: contains CR/LF (header injection attempt)`);
  }
}

function assertSafeFilename(value: string, field: string): void {
  assertNoHeaderInjection(value, field);
  if (/["\\]/.test(value)) {
    throw new Error(`[gmail] invalid ${field}: contains quote or backslash`);
  }
}

/**
 * Build an RFC 2822 message (multipart/mixed when there are attachments)
 * and return it base64url-encoded, the format Gmail API expects.
 *
 * Throws on CR/LF in recipient/subject/filename fields to prevent header
 * injection (BCC smuggling via untrusted LLM output).
 */
export function buildMimeMessage(params: EmailParams): string {
  // Validate every recipient and the subject for CR/LF before interpolating.
  const toArr = Array.isArray(params.to) ? params.to : [params.to];
  const ccArr = params.cc ? (Array.isArray(params.cc) ? params.cc : [params.cc]) : [];
  const bccArr = params.bcc ? (Array.isArray(params.bcc) ? params.bcc : [params.bcc]) : [];
  toArr.forEach((v, i) => assertNoHeaderInjection(v, `to[${i}]`));
  ccArr.forEach((v, i) => assertNoHeaderInjection(v, `cc[${i}]`));
  bccArr.forEach((v, i) => assertNoHeaderInjection(v, `bcc[${i}]`));
  assertNoHeaderInjection(params.subject, 'subject');

  const toList = toArr.join(', ');
  const ccList = ccArr.length > 0 ? ccArr.join(', ') : null;
  const bccList = bccArr.length > 0 ? bccArr.join(', ') : null;

  const boundary = `fujitrace_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
  const headers: string[] = [
    `To: ${toList}`,
    `Subject: ${encodeHeader(params.subject)}`,
    'MIME-Version: 1.0',
  ];
  if (ccList) headers.push(`Cc: ${ccList}`);
  if (bccList) headers.push(`Bcc: ${bccList}`);

  const hasAttachments = (params.attachments?.length ?? 0) > 0;
  const body = params.body;

  let raw: string;
  if (!hasAttachments) {
    headers.push('Content-Type: text/plain; charset="UTF-8"');
    headers.push('Content-Transfer-Encoding: base64');
    raw = `${headers.join('\r\n')}\r\n\r\n${Buffer.from(body, 'utf8').toString('base64')}`;
  } else {
    headers.push(`Content-Type: multipart/mixed; boundary="${boundary}"`);
    const parts: string[] = [];
    parts.push(`--${boundary}`);
    parts.push('Content-Type: text/plain; charset="UTF-8"');
    parts.push('Content-Transfer-Encoding: base64');
    parts.push('');
    parts.push(Buffer.from(body, 'utf8').toString('base64'));
    for (const att of params.attachments ?? []) {
      assertSafeFilename(att.filename, `attachment.filename`);
      assertSafeFilename(att.mimeType, `attachment.mimeType`);
      parts.push(`--${boundary}`);
      parts.push(`Content-Type: ${att.mimeType}; name="${att.filename}"`);
      parts.push(`Content-Disposition: attachment; filename="${att.filename}"`);
      parts.push('Content-Transfer-Encoding: base64');
      parts.push('');
      parts.push(att.base64);
    }
    parts.push(`--${boundary}--`);
    raw = `${headers.join('\r\n')}\r\n\r\n${parts.join('\r\n')}`;
  }

  // Gmail API wants base64url with no padding.
  return Buffer.from(raw, 'utf8').toString('base64url');
}

function encodeHeader(value: string): string {
  // If the header has non-ASCII characters, RFC 2047 encode it.
  // eslint-disable-next-line no-control-regex
  if (/[^\x00-\x7F]/.test(value)) {
    return `=?UTF-8?B?${Buffer.from(value, 'utf8').toString('base64')}?=`;
  }
  return value;
}

// ---------------------------------------------------------------------------
// Connector implementation
// ---------------------------------------------------------------------------

export const gmailConnector: Connector = {
  provider: 'google',
  requiredScopes: GOOGLE_GMAIL_SCOPES,

  async isConnected(userId: string): Promise<boolean> {
    return isConnectorLinked(userId, 'google');
  },

  async execute(userId: string, action: string, params: unknown): Promise<ConnectorActionResult> {
    if (!isGmailAction(action)) {
      return connectorErr(`Unknown gmail action: ${action}`, 'unknown_action');
    }
    if (!isEmailParams(params)) {
      return connectorErr('Invalid email params (to/subject/body required)', 'invalid_params');
    }

    const client = await buildGmailClient(userId);
    if (!client) {
      return connectorErr('Gmail is not connected for this user', 'not_connected');
    }

    try {
      const raw = buildMimeMessage(params);
      if (action === 'draftEmail') {
        const res = await client.users.drafts.create({
          userId: 'me',
          requestBody: { message: { raw } },
        });
        return connectorOk({ draftId: res.data.id ?? null, messageId: res.data.message?.id ?? null });
      }
      if (action === 'sendEmail') {
        const res = await client.users.messages.send({
          userId: 'me',
          requestBody: { raw },
        });
        return connectorOk({ messageId: res.data.id ?? null, threadId: res.data.threadId ?? null });
      }
      return connectorErr(`Unhandled gmail action: ${action as string}`, 'unknown_action');
    } catch (err) {
      return connectorErr(formatError(err), 'provider_error');
    }
  },
};

function formatError(err: unknown): string {
  if (err instanceof Error) return err.message;
  return String(err);
}
